apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels: 
    app: demo-voting-app
    name: result-service

spec: 
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 80
  selector: 
      app: demo-voting-app
      name: result-app-pod
